package com.pt_plus.cons;

public interface AppCons {
    String YYYY_MMM_DD_HH_MM_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'";
    int PRODUCT_LIST_TYPE_BEST_SELLER = 100;
    int PRODUCT_LIST_TYPE_NEW_ARRIVALS = 101;
    int PRODUCT_LIST_TYPE_CATEGORY = 102;
    int PRODUCT_LIST_TYPE_TARINER_FAV_PRODUCTS = 103;
    int PRODUCT_LIST_TYPE_RELATED_PRODUCTS = 104;
    int PRODUCT_LIST_TYPE_CENTETR_PRODUCTS = 105;
    int PRODUCT_LIST_TYPE_FILTER = 106;

    int TRAINER_LIST_TYPE_ALL = 200;
    int TRAINER_LIST_TYPE_FILTER = 201;
    int TRAINER_LIST_TYPE_FILTER_ACTIVITY_FILTER = 202;
    int TRAINER_LIST_TYPE_CENTER_TRAINERS = 203;

    //   center
    int CENTER_LIST_TYPE_ALL = 300;
    int CENTER_LIST_TYPE_CATEGORY = 301;

    String DATE_FORAMTE = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'";

    int GENERAL_WEBVIEW_TYPE_PRIVACY = 10;
    int GENERAL_WEBVIEW_TYPE_TERMECE = 20;


    int GALLERY_LIST_TYPE_TARINER = 100;
    int GALLERY_LIST_TYPE_CENTER = 101;


//     plan types

    int PLAN_LIST_TYPE_TRAINER = 200;
    int PLAN_LIST_TYPE_CENTER = 201;
}
